#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#USUARIO CONTROLLER
usuarios:
  path: /usuarios
  controller: App\Controller\UserController::usuarios
  methods: [GET,POST]

usuario:
  path: /usuarios/{id}
  controller: App\Controller\UserController::usuario
  methods: [GET,PUT,DELETE]
