#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#USUARIO CONTROLLER
usuarios:
  path: /usuarios
  controller: App\Controller\UserController::usuarios
  methods: [GET,POST]

usuario:
  path: /usuarios/{id}
  controller: App\Controller\UserController::usuario
  methods: [GET,PUT,DELETE]

consultarPlan:
  path: /usuarios/{id}/plan
  controller: App\Controller\UserController::consultarPlan
  methods: [GET]

activarPremium:
  path: /usuarios/{id}/premium
  controller: App\Controller\UserController::premium
  methods: [POST]


#PAGOS CONTROLLER

suscripciones: #
  path: /usuarios/{id}/suscripciones #SACAMOS TODOS LOS PAGOS DE EL USUARIO
  controller: App\Controller\PagosController::suscripciones
  methods: [GET]

#AQUI SACAMOS TODA LA INFO DE UNA SUPSCRICPIONES(PAGO)
supscripcion:
  path: /suscripciones/{id}
  controller: App\Controller\PagosController::suscripcion
  methods: [ GET ]

#CONFIG CONTROLLER


configuracion:
  path: /usuarios/{id}/configuracion
  controller: App\Controller\ConfiguracionController::configuracionUser
  methods: [GET]


cambiarconfiguracion:
  path: /usuarios/{id}/configuracion
  controller: App\Controller\ConfiguracionController::cambiarConfiguracion
  methods: [PUT]


#PLAYLIST CONTROLLER

playlistUser:
  path: /usuarios/{id}/playlists
  controller: App\Controller\PlaylistController::playlists
  methods: [GET,POST]

playlistDetalles:
  path: /playlists/{id}
  controller: App\Controller\PlaylistController::playlistDetail
  methods: [GET]
